### ISSUE TITLE
Implement

### ISSUE THREAD

**Issue by JamesMGreene** [JamesMGreene/node-flexunit#1]
**NOTE:** Basically model this module after the [JamesMGreene/node-flex-sdk](https://github.com/JamesMGreene/node-flex-sdk/) module

**TODO:**
- [ ] Install script to download FlexUnit from one of its Apache mirrors
  - Randomly select a mirror at runtime, or just pick a a single one [or a small subset] and go with that?
  - See "Current Release (x.y.z)" section of the ["Download Apache FlexUnit" page](http://flex.apache.org/download-flexunit.html), click on the link matching the RegExp `/apache-flex-flexunit-([\d]+\.[\d]+\.[\d]+)(.*)-bin\.zip/i`, e.g. http://www.apache.org/dyn/closer.cgi/flex/flexunit/4.2.0/binaries/apache-flex-flexunit-4.2.0-4.12.0-bin.zip
- [ ] Use [[to-be-implemented]](https://github.com/JamesMGreene/node-standalone-flash/issues/1) [JamesMGreene/node-standalone-flash](https://github.com/JamesMGreene/node-standalone-flash/) as an NPM peerDependency
- [ ] Use [JamesMGreene/node-flex-sdk](https://github.com/JamesMGreene/node-flex-sdk/) as an NPM peerDependency
- [ ] Provide a simple sub-module (a la "lib/flex.js" in `flex-sdk`) to wrap calling out to the FlexUnit JAR
  - May need to specify the `flex-sdk` location (as an environment variable, I think? e.g. `FLEX_HOME`)
  - May need to set some default JVM args, environment variables, etc.
  - May need to start the standalone Flash Player debugger/projector executable (from [JamesMGreene/node-standalone-flash](https://github.com/JamesMGreene/node-standalone-flash/))

**Comment by JamesMGreene** [comment]
Dependent on:
- https://github.com/JamesMGreene/node-standalone-flash/issues/1
